# PUT A Records
PUT http://18.169.249.10:3001/domains/bulknames.link/update
Content-Type: application/json

{
    "type":"A",
    "value":[
        {
            "class": "IN",
            "type": "A",
            "name": "testnames.link",
            "data": "18.169.249.10",
            "ttl": 3600
        },
        {
            "class": "IN",
            "type": "A",
            "name": "www.testnames.link",
            "data": "18.169.249.10",
            "ttl": 3600
        },
        {
            "class": "IN",
            "type": "A",
            "name": "ns1.testnames.link",
            "data": "18.169.249.10",
            "ttl": 3600
        },
        {
            "class": "IN",
            "type": "A",
            "name": "ns2.testnames.link",
            "data": "18.169.249.10",
            "ttl": 3600
        }
    ]
}