# PUT A Records
PUT http://18.169.249.10:3001/domains/testnames.link/update
Content-Type: application/json

{
    "type":"NS",
    "value":[
        {
            "class": "IN",
            "type": "NS",
            "name": "testnames.link",
            "data": "ns1.testnames.link",
            "ttl": 3600
        },
        {
            "class": "IN",
            "type": "NS",
            "name": "testnames.link",
            "data": "ns2.testnames.link",
            "ttl": 3600
        }
    ]
}